Added missing self
Фикс за тази грешка:
Error: instance member 'name' cannot be used on type 'DataType'
        var swiftCode:String = "class \(name) {"